version: "3"

networks:
  docknet:
    external: true

services:
  registry-service:
    image: syamsularie/registry-servicei:main
    container_name: registry-service
    restart: always
    networks:
      - docknet
    volumes:
      - ./config-registry:/config
      - ./logs/partner:/logs

  transaction-service:
    image: syamsularie/transction-service:main
    container_name: transaction-service
    restart: always
    networks:
      - docknet
    volumes:
      - ./config-transaction:/config
      - ./logs/transaction:/logs
    ports:
      - 9000:9000

  drools-service:
    image: syamsularie/drools-service:main
    container_name: drools-service
    restart: always
    networks:
      - docknet
    volumes:
      - ./config-drools:/config
      - ./logs/partner:/logs

  mailer-service:
    image: syamsularie/mailer-service:main
    container_name: mailer-service
    restart: always
    networks:
      - docknet
    volumes:
      - ./config-mailer:/config
      - ./logs/partner:/logs
volumes:
  config:
