server:
  port: 9000
  address: 0.0.0.0

spring:
  datasource:
#    url: "jdbc:postgresql://prodigy-dev.cnq1usdro1p4.ap-southeast-3.rds.amazonaws.com:5432/syamsulcashback"
    url: "jdbc:postgresql://localhost:5432/syamsulcashback"
    username: "syamsulbac"
    password: "1234567890"
    driver: "org.postgresql.Driver"
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.format_sql: true
    hibernate.jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  application.name: TRANSACTION-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

integration:
  aws-cognito:
    access-key: "AKIA2WLDYKX5GR7IAI66"
    secret-key: "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"
    region: "ap-southeast-1"
    jwks: '{"keys":[{"alg":"RS256","e":"AQAB","kid":"WH1E7MoDJY4GbMzwt5R5Mf5vuPtZuynwCvvh7GNDSGo=","kty":"RSA","n":"_4InA9eh7t1dDzb0thODTWCXCxlXasSSvsiuEJwJ2MdYahlD8j4jlMw8_w6o94Pt-BN_MwkKNxMP7I-Z1QyNg-AwwJteYmaJsJ5YfHhhyf0cn0BxsgFHRz-nZuYCvFKtRp9zICgHEb5wZyG07g7Z_3Bdy9CGECHbUl6x3XsA8ltmSpNEwcNio-1lw0alS7eftxROwK7e6MWZJ3x_Qd8xMBT_IpVZBq7hIf8f9XY3fZArT0aR4POc3Folvah2XfD4BSDkVVILdw4sBaJ3LafSFVIQdcVtC5EhgtoclWG-cG7k05EeLNAng_T3dpTDvbMaKRp_If8T6VTW4KpiOKQcXw","use":"sig"},{"alg":"RS256","e":"AQAB","kid":"9CChmx5QcbP4i9wf4M7ds7y9ivrf3uPQYzkPcfvgLa8=","kty":"RSA","n":"zN4h5BZKYmVTGZlvqm-OYPe6eH-ZkBoPcBv0wJTncoGAC0DiO1ZfBzf92xw5lbizfCOhFYmysK46EDeIxUv94R5VMmx6PhSlesYYoB4Uh-eAzP1lDes9vVcsowagPxP6KftEWdT6TA-f_S6Kl0Exl3xxJ6ky36BrSMBa7x9wwB4_Num6nqxliCr10LrIsTVkYk-AOSe2Jmk5LbwgUdrD8ITelyr744kYMNa_kViMy7EjvrdREr4amu_GXVCYshCSH3NmLjI2weHZRXCM6oOP-8tzzX_CCbFbCqckZpasDWKAFzSSHxFDX2DFLd1A-dFTay42tZqLG-PUrAu8sY5xdQ","use":"sig"}]}'
    clientid: "2vvunnoq32oocjq26j8ed0pk5n"
    secret: "c4nvabss26c4scgdem5dan9cuvv49ac1mhgbgt894c81ee9f970"
  aws-ses:
    region: "ap-southeast-3"
    access-key: "AKIA2WLDYKX5GR7IAI66"
    secret-key: "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"
  aws-sqs:
    region: "ap-southeast-3"
    access-key: "AKIA2WLDYKX5GR7IAI66"
    secret-key: "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"
    queue-url: "https://sqs.ap-southeast-3.amazonaws.com/735185491450/kezbek-notification-email"
    queue-name: "kezbek-notification-email"
